spring:
  application:
    name: springboot-layui-demo01
  ############### H2 Begin ################
  datasource:
    driver-class-name: org.h2.Driver
    # default dbc:h2:mem:testdbsa
    url: jdbc:h2:mem:testdbsa
    username: sa
    # default null
    password:
    # db schema
    schema: classpath:db/schema.sql
    # db data
    data: classpath:db/data.sql
  h2:
    console:
      settings:
        web-allow-others: true #remote visit
        trace: true
      path: /h2-console # console url
      enabled: true
  ############### static resources begin ################
  #  resources:
  #    static-locations: classpath:static/,file:static/,

  ############### static resources end ################
  #  thymeleaf:
  #    mode: HTML5
  #    encoding: UTF-8
  #    cache: false
  #    prefix: classpath:/templates
  #    suffix: .html
  #    servlet:
  #      content-type: text/html; charset=utf-8
  freemarker:
    suffix: .html





############### H2 End ################

############### Mybatis Begin ################
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-io-camel-core: true
############### Mybatis end ################

############### Log Begin################
logging:
  level:
    com.boot.study.mapper: TRACE
#    org:
#      hibernate: DEBUG
#  config: classpath:logback-boot.xml
############### Log End ################


############### Port Begin ################
server:
  port: 8080

############### Port End ################
