#服务端口
server:
  port: 8071

#jdbc
spring:
  datasource:
    username: root
    password: mysql
    url: jdbc:mysql://localhost:3306/gmall_study?useUnicode=true&characterEncoding=utf-8&useSSL=false
  #dubbo 配置
  dubbo:
    application: gmall-manager-service
    registry:
      # zookeeper 的通讯协议的名称
      address: 172.16.144.130:2181
      # zookeeper 的通讯协议名称
      protocol: zookeeper
    # dubbo的通讯协议名称
    protocol:
      name: dubbo
    # dubbo服务的扫描路径
    base-package: com.gardenia.gmall

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-io-camel-core: true

# 日志
logging:
  level:
    root: debug






